###############
# Application #
###############

app:
  # Main info
  title: "My title"
  description: "My description"

  # News sections (default config)
  # - Title and url are optional
  # - Max is the maximum number of posts for each blog
  # - Flags author, date and category could be overriden too
  blogs:
    enabled: 1
    max: 20
    interval: "2 weeks"
    author: 1
    category: 0
    date: 1
    reverse: 0

  # Twitter section
  # - Tag and url are optional
  tweets:
    enabled: 1
    max: 20
    tag: "#news"
    title: "Tweets"

  # Calendar section
  # - Url is optional
  events:
    enabled: 1
    interval: "1 week"
    title: "Agenda"
    url: "http://calendar.net"

  # More info
  credits: 
    - 'Builded by <a href="https://github.com/pepe84/social-digest">social-digest system</a>'

  # Digest output
  output:
    # File to generate
    file:
      # Full version includes html, head and body tags
      full: 1
      # Destination
      path: "digest.html"
    # CSS style, inline or path (optional)
    style:
      inline:
        "h2": "background-color: #999; color: #fff; padding: 4px 10px;"
        "a.article-link": "display: block; color: #fff; text-decoration: none;"
        "ul": "list-style-type: none; margin: 0; padding: 0 14px;"
        "li": "margin: 0; border-bottom: 1px solid #eee; padding: 6px 0px;"
        "li": "margin: 0; border-bottom: 1px solid #eee; padding: 6px 0px;"
        "footer": "margin-top: 24px; border-top: 4px solid #999; padding-top: 20px;"
    # Optional mail delivery, very useful if you want to send content to a mailing 
    # list or to upload a new WP post (http://jetpack:me/support/post-by-email)
    # Note: If is enabled, full output is automatically disabled
    mail:
      enabled: 0
      to: "xxx@post.wordpress.com"
      from: "xxx@gmail.com"
      bcc: "xxx@googlegroups.com"
      append: "<p style='display:none'>[category Info]</p>"

########
# Mail #
########

#mail:
#  host:       localhost
#  port:       25
#  username:   your_username
#  password:   your_password
#  encryption: ssl

############
# Services #
############

services:
  # Google API v3
  google:
    apiKey: "FILL-ME-PLEASE"
    calendar:
      endpoint: "https://www.googleapis.com/calendar/v3"
  # Bit.ly API v3
  bitly:
    apiKey: "FILL-ME-PLEASE"
    endpoint: "https://api-ssl.bitly.com/v3"
  # TODO Use Twitter API v1.1 https://dev.twitter.com/docs/api/1.1
  # TODO Use TwitterOAuth lib https://github.com/abraham/twitteroauth
  twitter:
    urls:
      profile: "https://twitter.com/%username"
      status: "https://twitter.com/%username/status/%id"
      search: "https://twitter.com/search?q=%query"

################
# Translations #
################

translations:
  Mon: "Dl"
  Tue: "Dm"
  Wed: "Dx"
  Thu: "Dj"
  Fri: "Dv"
  Sat: "Ds"
  Sun: "Dg"
  No author: "Sense autor"
  No category: "Sense categoria"