###############
# Application #
###############

app:
  # Main info
  title: "Notícies dels diaris"
  description: "Portada"
  
  # Optional (see http://www.php.net/manual/en/timezones.php)
  timezone: "Europe/Madrid"
  
  # Calendar section
  # - url is optional
  events:
    enabled: 1
    # Info
    title: "Agenda"
    # Filter
    interval: "1 week"
    
  # News sections default config (could be overriden at feeds.yml)
  # - url and tag are optional
  # - max is the maximum number of allowed posts for each feed
  news:
    enabled: 1
    # Filter
    max: 5
    interval: "10 days"
    # Group by
    author: 1
    date: 0
    # Sort by
    reverse: 0
    
  # Twitter section
  # - url and tag are optional
  tweets:
    enabled: 0
    # Info
    title: "Piulades"
    # Filter
    max: 20
    tag: "#noticies"

  # More info
  credits: 
    - 'Builded by <a href="https://github.com/pepe84/social-digest">social-digest</a> system'
    
  # Digest output
  output:
    # File to generate
    file:
      # Full version includes html, head and body tags
      full: 1
      # Destination
      path: "./news.html"
    # CSS style, inline or path (optional)
    style:
      inline:
        "h2": "background-color: #999; color: #fff; padding: 4px 10px;"
        "a.section-link": "display: block; color: #fff; text-decoration: none;"
        "ul": "list-style-type: none; margin: 0; padding: 0 14px;"
        "li": "margin: 0; border-bottom: 1px solid #eee; padding: 4px 0px;"
        "div.credits": "margin-top: 24px; border-top: 4px solid #999; padding-top: 20px;"
        "div.event-summary": "margin-bottom: 4px;"
        "div.event-location": "font-size: 0.8em;"
    # Optional mail delivery, very useful if you want to send content to a mailing 
    # list or to upload a new WP post (http://jetpack.me/support/post-by-email)
    # Note: If is enabled, full output is automatically disabled
    mail:
      enabled: 1
      from:
        - "socialdigest@mailinator.com"
      to:
        - "socialdigestest1@mailinator.com"
        - "socialdigestest2@mailinator.com"
      cc:
        - "socialdigestestcc@mailinator.com"
      bcc:
        - "socialdigestestcco@mailinator.com"
      
###############################
# Database sources (optional) #
###############################

db:
  # Connection
  conn:
    dbname:   "social-digest-test"
    user:     "tester"
    password: "secret"
    host:     "localhost"
    driver:   "pdo_mysql"
    charset:  "utf8"
  # Configuration
  conf:
    # News sources
    feeds:
      table: "users"
      columns:
        # Mandatory
        src:  "blog"
        cat:  "category"
        # Optional
        key:  "name"
        mail: "mail"
    # Events sources
    calendars:
      table:  "users"
      columns:
        # Mandatory
        src:  "calendar"

########
# Mail #
########

mail:
  host:       "localhost"
  port:       25
  username:   "YOUR-USERNAME"
  password:   "YOUR-PASSWORD"
  encryption: "ssl"
  
############
# Services #
############

services:
  # Google API v3
  google:
    apiKey: "FILL-ME-PLEASE"
    calendar:
      endpoint: "https://www.googleapis.com/calendar/v3"
  # Bit.ly API v3
  bitly:
    apiKey: "FILL-ME-PLEASE"
    endpoint: "https://api-ssl.bitly.com/v3"
  # TODO Use Twitter API v1.1 https://dev.twitter.com/docs/api/1.1
  # TODO Use TwitterOAuth lib https://github.com/abraham/twitteroauth
  twitter:
    urls:
      profile: "https://twitter.com/%username"
      status:  "https://twitter.com/%username/status/%id"
      search:  "https://twitter.com/search?q=%query"
  
################
# Translations #
################

translations:
  Mon: "Dl"
  Tue: "Dm"
  Wed: "Dx"
  Thu: "Dj"
  Fri: "Dv"
  Sat: "Ds"
  Sun: "Dg"
  No author: "Sense autor"
  No category: "Sense categoria"